version: '3'
services:
  nginx:
    container_name: nginx
    restart: on-failure
    build:
      context: ./nginx
      args:
        - APPHOMEDIR
        - USERNAME
        - USER_UID
        - USER_GID
        - STATICROOT_NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - app_static:/usr/share/nginx/html/static:ro
    ports:
      - 8000:80

  app-admin:
    container_name: app-admin
    restart: on-failure
    build:
      context: ./app
      args:
        - APPHOMEDIR
        - USERNAME
        - USER_UID
        - USER_GID
        - STATICROOT
    env_file:
      - ./app/.env
    volumes:
      - app_static:/var/www/static
    depends_on:
      - postgres
    entrypoint: gunicorn config.asgi:django_application --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  app-api:
    container_name: app-api
    restart: on-failure
    build:
      context: ./app
      args:
        - APPHOMEDIR
        - USERNAME
        - USER_UID
        - USER_GID
        - STATICROOT
    env_file:
      - ./app/.env
    depends_on:
      - postgres
    entrypoint: gunicorn config.asgi:fastapi_application --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  etl:
    container_name: etl
    restart: on-failure
    build:
      context: ./etl
      args:
        - APPHOMEDIR
        - USERNAME
        - USER_UID
        - USER_GID
    env_file:
      - ./etl/.env
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:15.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  rabbitmq:
    container_name: rabbitmq
    restart: on-failure
    build: ./rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  redis:
    container_name: redis
    restart: on-failure
    image: bitnami/redis:7.0.9
    environment:
      - REDIS_PASSWORD
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb

volumes:
  app_static:
  pgdata:
  rabbitmq:
