# Generated by Django 4.2 on 2023-06-20 09:16

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import psqlextra.indexes.unique_index
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            'notify',
            'notify_schema'
        )
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'notify"."messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='CREATED', editable=False, max_length=10, verbose_name='status')),
                ('users_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None, verbose_name='users_ids')),
                ('is_instant', models.BooleanField(default=True, verbose_name='is_instant')),
                ('schedule_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='schedule_at')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notify"."notifications',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('layot', tinymce.models.HTMLField(verbose_name='layot')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'notify"."templates',
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=psqlextra.indexes.unique_index.UniqueIndex(fields=['name', 'layot'], name='template_name_layot_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.template', verbose_name='Template'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=psqlextra.indexes.unique_index.UniqueIndex(fields=['name', 'subject', 'body'], name='message_name_subject_body_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notification_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['modified_at'], name='notification_modified_idx'),
        ),
    ]
