# Generated by Django 4.2 on 2023-06-23 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import psqlextra.indexes.unique_index
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=80, unique=True, verbose_name="username")),
                ("email", models.EmailField(max_length=120, unique=True, verbose_name="email")),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": 'notify"."users',
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified_at")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="first_name")),
                ("last_name", models.CharField(max_length=64, verbose_name="last_name")),
                ("timezone", models.CharField(verbose_name="timezone")),
            ],
            options={
                "verbose_name": "User info",
                "verbose_name_plural": "Users info",
                "db_table": 'notify"."users_info',
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notify.message",
                verbose_name="Message",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="schedule_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Укажите в случае, если вы сняли галку в пункте 'Мгновенная отправка' и хотите отправить уведомление отложенно",
                verbose_name="schedule_at",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="notify.template",
                verbose_name="Template",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("template", "message", "users_ids", "schedule_at"),
                name="unique_notification_for_users_ids",
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="info",
                to="notify.user",
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="userinfo",
            index=psqlextra.indexes.unique_index.UniqueIndex(
                fields=["user", "first_name", "last_name"], name="info_user_first_last_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userinfo",
            constraint=models.UniqueConstraint(
                fields=("user", "first_name", "last_name"),
                name="unique_first_last_name_for_user_id",
            ),
        ),
    ]
