# Generated by Django 4.2 on 2023-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0002_user_userinfo_alter_notification_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="additional_info",
            field=models.JSONField(
                blank=True,
                default={},
                help_text="Любая дополнительная информация для шаблонав формате ключ-значение, например {'user_from_id': 'c9212aef-0959-4b94-aee2-5cf9c9ae6bd1'}",
                null=True,
                verbose_name="additional_info",
            ),
        ),
    ]
